services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=CleverBank'
      - 'POSTGRES_PASSWORD=12345678'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    build:
      dockerfile: Dockerfile
volumes:
  postgres-data: