create table if not exists Banks
(
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(50)
    );

create table if not exists Users
(
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(50) NOT NULL UNIQUE ,
    password varchar(50) NOT NULL
    );

create table if not exists Accounts
(
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    owner_bank_id int REFERENCES Banks(id) ON DELETE CASCADE ,
    owner_user_id int REFERENCES Users(id) ON DELETE CASCADE ,
    amount DECIMAL(30, 2),
    created_at date DEFAULT CURRENT_TIMESTAMP
    );

CREATE TYPE Operation_enum AS ENUM ('REPLENISHMENT', 'WITHDRAWAL', 'TRANSFER');

create table if not exists Transactions
(
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    sender_account_id int REFERENCES Accounts(id),
    beneficiary_account_id int REFERENCES Accounts(id),
    amount DECIMAL(30, 2),
    operation_type Operation_enum,
    created_at date DEFAULT CURRENT_TIMESTAMP
    );